/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DunningRouteImport } from './routes/dunning'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions.$id'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DunningRoute = DunningRouteImport.update({
  id: '/dunning',
  path: '/dunning',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dunning': typeof DunningRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/webhooks': typeof WebhooksRoute
  '/customers/$id': typeof CustomersIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dunning': typeof DunningRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/webhooks': typeof WebhooksRoute
  '/customers/$id': typeof CustomersIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/customers': typeof CustomersIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dunning': typeof DunningRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/webhooks': typeof WebhooksRoute
  '/customers/$id': typeof CustomersIdRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/dunning'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/portal'
    | '/register'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/webhooks'
    | '/customers/$id'
    | '/subscriptions/$id'
    | '/customers/'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dunning'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/portal'
    | '/register'
    | '/settings'
    | '/transactions'
    | '/webhooks'
    | '/customers/$id'
    | '/subscriptions/$id'
    | '/customers'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dashboard'
    | '/dunning'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/portal'
    | '/register'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/webhooks'
    | '/customers/$id'
    | '/subscriptions/$id'
    | '/customers/'
    | '/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DunningRoute: typeof DunningRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  PortalRoute: typeof PortalRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dunning': {
      id: '/dunning'
      path: '/dunning'
      fullPath: '/dunning'
      preLoaderRoute: typeof DunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface SubscriptionsRouteChildren {
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DunningRoute: DunningRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  PortalRoute: PortalRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
